// ===========================================================
// BetaLabsPage — auto-discovers beta projects from manifest.json.
// Generated by the Vite plugin at build/dev time by scanning
// public/beta-projects/. No hardcoding needed.
// ===========================================================

import { useState, useEffect } from 'react';
import { useRouter } from '../state/router';
import { GlassPanel, SectionHeader, Chip } from '../components/ui';
import { BetaCard } from '../components/BetaCard';
import { Icon } from '../components/Icon';
import type { BetaProject } from '../data/betaLabs';

type LoadState = 'loading' | 'ready' | 'empty' | 'error';

export function BetaLabsPage() {
  const { navigate } = useRouter();
  const [projects, setProjects] = useState<BetaProject[]>([]);
  const [state, setState] = useState<LoadState>('loading');

  useEffect(() => {
    fetch('/beta-projects/manifest.json')
      .then((r) => {
        if (!r.ok) throw new Error('Manifest not found');
        return r.json();
      })
      .then((data: BetaProject[]) => {
        setProjects(data);
        setState(data.length === 0 ? 'empty' : 'ready');
      })
      .catch(() => setState('error'));
  }, []);

  return (
    <div className="space-y-8">
      <SectionHeader
        eyebrow="Experimental"
        title="Beta Labs"
        description="Test bleeding-edge learning environments before they become official. Your feedback directly shapes Quantum Core."
      />

      {/* Warning banner */}
      <GlassPanel className="border-warn-400/30 bg-warn-400/5 p-5">
        <div className="flex items-start gap-4">
          <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg border border-warn-400/30 bg-warn-400/10">
            <Icon name="AlertTriangle" size={18} className="text-warn-400" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h3 className="font-display text-lg font-semibold text-white">Experimental Environments</h3>
              <Chip variant="warn">Experimental</Chip>
            </div>
            <p className="mt-1 text-sm leading-relaxed text-slate-400">
              These labs are under active development. Features may be incomplete or change without notice.
              Your feedback helps identify bugs, improve usability, and prioritize new features.
            </p>
          </div>
        </div>
      </GlassPanel>

      {/* Project grid */}
      {state === 'loading' && (
        <div className="flex items-center justify-center py-16">
          <div className="flex flex-col items-center gap-4">
            <div className="h-8 w-8 animate-spin rounded-full border-2 border-neon-400/30 border-t-neon-400" />
            <span className="font-mono text-[11px] uppercase tracking-wider text-slate-500">
              Scanning beta projects...
            </span>
          </div>
        </div>
      )}

      {state === 'ready' && (
        <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
          {projects.map((project) => (
            <BetaCard
              key={project.slug}
              project={project}
              onClick={() => navigate(`/beta/${project.slug}`)}
            />
          ))}
        </div>
      )}

      {state === 'empty' && (
        <GlassPanel className="flex flex-col items-center justify-center py-16 text-center">
          <Icon name="FlaskConical" size={40} className="text-slate-600" />
          <h3 className="mt-4 font-display text-lg text-slate-300">No Beta Projects Yet</h3>
          <p className="mt-2 max-w-md text-sm text-slate-500">
            Drop a folder with an <code className="text-cyan-400">index.html</code> into{' '}
            <code className="text-neon-300">public/beta-projects/</code> and it will appear here automatically.
          </p>
        </GlassPanel>
      )}

      {state === 'error' && (
        <GlassPanel className="flex flex-col items-center justify-center py-16 text-center">
          <Icon name="AlertCircle" size={40} className="text-err-400" />
          <h3 className="mt-4 font-display text-lg text-slate-300">Could Not Load Projects</h3>
          <p className="mt-2 max-w-md text-sm text-slate-500">
            The manifest could not be fetched. Make sure the dev server is running and the Vite plugin has generated{' '}
            <code className="text-cyan-400">public/beta-projects/manifest.json</code>.
          </p>
        </GlassPanel>
      )}

      {/* How to add hint */}
      <GlassPanel className="border-dashed border-white/10 p-5">
        <div className="flex items-start gap-4">
          <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg border border-white/10 bg-white/[0.02]">
            <Icon name="Plus" size={18} className="text-slate-500" />
          </div>
          <div>
            <h3 className="font-display text-base font-semibold text-slate-300">Adding a New Beta Project</h3>
            <ol className="mt-2 space-y-0.5 text-sm text-slate-500">
              <li>1. Create <code className="text-neon-300">public/beta-projects/&lt;name&gt;/index.html</code></li>
              <li>2. Optionally add <code className="text-cyan-400">meta.json</code> for custom title, description, version</li>
              <li>3. The card appears here automatically — no React changes needed</li>
            </ol>
          </div>
        </div>
      </GlassPanel>
    </div>
  );
}
