// ===========================================================
// BetaCard — card for a single auto-discovered beta project.
// Props come from the manifest.json generated by the Vite plugin.
// ===========================================================

import { Icon } from './Icon';
import { GlassPanel, ProgressBar } from './ui';
import { cn } from '../lib/cn';
import type { BetaProject, BetaProjectStatus } from '../data/betaLabs';

interface BetaCardProps {
  project: BetaProject;
  onClick?: () => void;
}

const statusColors: Record<BetaProjectStatus, string> = {
  experimental: 'text-warn-400 border-warn-400/40 bg-warn-400/10',
  alpha:        'text-orange-400 border-orange-400/40 bg-orange-400/10',
  beta:         'text-cyan-400 border-cyan-400/40 bg-cyan-400/10',
  preview:      'text-neon-400 border-neon-400/40 bg-neon-400/10',
};

const statusLabels: Record<BetaProjectStatus, string> = {
  experimental: 'Experimental',
  alpha:        'Alpha',
  beta:         'Beta',
  preview:      'Preview',
};

export function BetaCard({ project, onClick }: BetaCardProps) {
  const status = (project.status as BetaProjectStatus) in statusColors
    ? (project.status as BetaProjectStatus)
    : 'experimental';

  return (
    <GlassPanel className="group flex cursor-pointer flex-col p-6 transition-all duration-300 hover:border-neon-400/30" hover onClick={onClick}>
      {/* Header */}
      <div className="flex items-start justify-between gap-4">
        <div className="flex h-12 w-12 items-center justify-center rounded-xl border border-white/10 bg-white/[0.03]">
          <Icon name={project.icon || 'FlaskConical'} size={22} className="text-neon-400 group-hover:text-glow transition-colors" />
        </div>
        <span className={cn('rounded-full border px-2.5 py-0.5 font-mono text-[10px] uppercase tracking-wider', statusColors[status])}>
          {statusLabels[status]}
        </span>
      </div>

      {/* Title */}
      <h3 className="mt-4 font-display text-xl font-semibold text-white">{project.title}</h3>

      {/* Description */}
      {project.description && (
        <p className="mt-2 line-clamp-2 flex-1 text-sm leading-relaxed text-slate-400">{project.description}</p>
      )}

      {/* Version */}
      <div className="mt-4 flex items-center gap-2 text-xs text-slate-500">
        <Icon name="Tag" size={11} />
        <span className="font-mono text-slate-400">{project.version}</span>
      </div>

      {/* Progress (only if set) */}
      {project.progress > 0 && (
        <div className="mt-4">
          <div className="mb-1.5 flex justify-between font-mono text-[10px]">
            <span className="text-slate-500">Dev Progress</span>
            <span className="text-neon-300">{project.progress}%</span>
          </div>
          <ProgressBar value={project.progress} />
        </div>
      )}

      {/* Tags */}
      {project.tags.length > 0 && (
        <div className="mt-3 flex flex-wrap gap-1.5">
          {project.tags.map((tag) => (
            <span key={tag} className="font-mono text-[10px] text-slate-600">#{tag}</span>
          ))}
        </div>
      )}

      {/* Launch button */}
      <button
        className={cn(
          'mt-5 w-full rounded-lg border border-neon-400/30 bg-neon-400/10 px-4 py-2.5',
          'font-mono text-[11px] uppercase tracking-wider text-neon-300',
          'transition-all duration-200 hover:border-neon-400/50 hover:bg-neon-400/20 hover:text-neon-200',
          'focus:outline-none focus:ring-2 focus:ring-neon-400/50',
        )}
        onClick={(e) => { e.stopPropagation(); onClick?.(); }}
      >
        Launch Beta
      </button>
    </GlassPanel>
  );
}
