// ===========================================================
// Beta Projects — types only.
// The actual project list is auto-generated by the Vite plugin
// into /public/beta-projects/manifest.json at build/dev time.
//
// To add a new project:
//   1. Create public/beta-projects/<slug>/index.html
//   2. Optionally create public/beta-projects/<slug>/meta.json
//   3. Done.
// ===========================================================

export type BetaProjectStatus = 'experimental' | 'alpha' | 'beta' | 'preview';

export interface BetaProject {
  slug: string;
  title: string;
  description: string;
  version: string;
  status: BetaProjectStatus;
  progress: number;
  icon: string;
  tags: string[];
}

export function betaProjectUrl(slug: string): string {
  return `/beta-projects/${slug}/index.html`;
}
